version: "3.4"

services:
  onlineretailer-apigateway:
    image: ${DOCKER_REGISTRY-}onlineretailer-apigateway
    build:
      context: .
      dockerfile: OnlineRetailer.APIGateway/Dockerfile
    depends_on:
      - onlineretailer-productapi
      - onlineretailer-orderapi
      - onlineretailer-customerapi

  onlineretailer-productapi:
    image: ${DOCKER_REGISTRY-}onlineretailer-productapi
    build:
      context: .
      dockerfile: OnlineRetailer.ProductAPI/Dockerfile

  onlineretailer-orderapi:
    image: ${DOCKER_REGISTRY-}onlineretailer-orderapi
    build:
      context: .
      dockerfile: OnlineRetailer.OrderAPI/Dockerfile

  onlineretailer-customerapi:
    image: ${DOCKER_REGISTRY-}onlineretailer-customerapi
    build:
      context: .
      dockerfile: OnlineRetailer.CustomerAPI/Dockerfile

  onlineretailer-prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - onlineretailer-productapi
      - onlineretailer-orderapi
      - onlineretailer-customerapi
      - onlineretailer-apigateway

  onlineretailer-grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - onlineretailer-prometheus
