version: '3.4'

services:
  onlineretailer.productapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002"

  onlineretailer.orderapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000"


  onlineretailer.customerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5004"

