version: '3.4'

services:
  onlineretailer.customerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  onlineretailer.orderapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  onlineretailer.productapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

