version: '3.4'

services:
  onlineretailer.customerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001"

  onlineretailer.orderapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002"


  onlineretailer.productapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003"
