version: '3.4'

services:
  onlineretailer.customerapi:
    image: ${DOCKER_REGISTRY-}onlineretailercustomerapi
    build:
      context: .
      dockerfile: OnlineRetailer.CustomerAPI/Dockerfile

  onlineretailer.orderapi:
    image: ${DOCKER_REGISTRY-}onlineretailerorderapi
    build:
      context: .
      dockerfile: OnlineRetailer.OrderAPI/Dockerfile


  onlineretailer.productapi:
    image: ${DOCKER_REGISTRY-}onlineretailerproductapi
    build:
      context: .
      dockerfile: OnlineRetailer.ProductAPI/Dockerfile

