global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "onlineretailer-apigateway"
    static_configs:
      - targets: ["onlineretailer-apigateway:80"]

  - job_name: "onlineretailer-orderapi"
    static_configs:
      - targets: ["onlineretailer-orderapi:80"]

  - job_name: "onlineretailer-productapi"
    static_configs:
      - targets: ["onlineretailer-productapi:80"]

  - job_name: "onlineretailer-customerapi"
    static_configs:
      - targets: ["onlineretailer-customerapi:80"]
