apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlineretailer-orderapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlineretailer-orderapi
  template:
    metadata:
      labels:
        app: onlineretailer-orderapi
    spec:
      containers:
        - name: onlineretailer-orderapi
          image: schemabuoi/onlineretailer-orderapi:latest
---
apiVersion: v1
kind: Service
metadata:
  name: onlineretailer-orderapi
  namespace: default
spec:
  type: NodePort
  selector:
    app: onlineretailer-orderapi
  ports:
    - port: 80
      nodePort: 31000
