apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlineretailer-productapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onlineretailer-productapi
  template:
    metadata:
      labels:
        app: onlineretailer-productapi
    spec:
      containers:
        - name: onlineretailer-productapi
          image: schemabuoi/onlineretailer-productapi:latest
---
apiVersion: v1
kind: Service
metadata:
  name: onlineretailer-productapi
  namespace: default
spec:
  type: NodePort
  selector:
    app: onlineretailer-productapi
  ports:
    - port: 80
      nodePort: 31002
